### ISSUE TITLE
Changes instances of the word Rom to RomHash

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#1020]
The Roms table is really a table of hashes.  It could be very easy for someone (or some bot) to get the wrong idea what we are storing in the database.  Let's be careful and change all instances of the word Rom with RomHash to be more accurate and reduce potential confusion.

**Comment by meshuggahtas** [comment]
There is only two word I've found to be might be confusable, Games and Roms.

https://tasvideos.org/Games
- Personally I'm okay with this naming, as it's also used for many other websites with zero links to copyrighted files of said video game. I personally don't vote on changing this, because "tasvideos" is clearly descriptive that we are talking about videos. Example websites: https://gamefaqs.gamespot.com/games https://www.mobygames.com/game/air-hockey__
- Maybe feos or Masterjun reported this on Discord on probably confusable. My suggestion would be rename to GameDB or something more descriptive which tells reader to interpret as a list of games used for categorizing purposes

Based on my above explanation, I suggest the following for "Roms" https://tasvideos.org/Games/1/Roms/List :
- Change Roms **for** Super Mario Bros. to Roms **of** Super Mario Bros.
- Add a SystemPage which has the same notice what we have probably at Movies about we don't host ROMs and use it for movies as well
- If we want to get rid of the word ROM for this particular area, we can just say Hashes. We are talking about video games and a checksum that equals to the content of the product without telling anyone what is the content. I'm unsure if this would be straightforward for others, so I don't personally suggest it, but might be better in different point of views

**Comment by adelikat** [comment]
This was completed.  It was changed to Game Version, but all instances were handled
