### ISSUE TITLE
Make certain unclickable site elements look less like a clickable button

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1021]
There are certain elements on the site that have exactly the style of a button, but aren't clickable.
I have a strong memory of being confused what is clickable and what is just styled text when I first browsed the site. (I mentioned it immediately in my first feedback, before working on stuff myself.)

This is even worse for mobile visitors since they don't have a cursor to check whether something is a link or not.

Here are some examples.

All site titles:
![image](https://user-images.githubusercontent.com/22375320/150160986-df539fc5-cc87-4d5c-814d-84139f360896.png)

The forum [highlight]:
![image](https://user-images.githubusercontent.com/22375320/150160770-554bf2d0-bc7e-4db4-83be-44c9322042cc.png)

The "Featured" on the frontpage:
![image](https://user-images.githubusercontent.com/22375320/150161881-e6117d58-6a92-44e7-902a-553d60eab378.png)

**Comment by TiKevin83** [comment]
Would you prefer to standardize clickable on the primary or secondary color?

**Comment by Masterjun3** [comment]
None, it's not the buttons that need to change.

**Comment by meshuggahtas** [comment]
Current type of links with examples from the opening issue text
- Normal text: DOS Jetpack by slamo in 32:22.55, Posted: 14 days ago (Edited: 14 days ago)
- Normal text with blue: Spikestuff, now freeware (lol)
- Rounded border rectangle: +, Latest Posts, Posts since last visit, Unanswered posts, Quote, Goal of this TAS: After using the unlock all homeworlds cheat code, Featured, Watch
- Image: no example from here but award for a user at profile/forum posts

Note to myself: there was a "Delete" button that looked like I could press it but it was actually disabled. Time to find it.

**Comment by Masterjun3** [comment]
The headings are fixed, which was the biggest part of this.
The others can *technically* be learned to not be buttons because we don't have buttons in that color anywhere else (I think).
So I'm closing this as completed. Thanks for the heading fix.
