### ISSUE TITLE
Search - Movie pages not likely to show

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#1052]
https://tasvideos.org/Search?SearchTerms=tomba

There is 1 published movie for this game.  The submission shows but not the publication.  This is because movie descriptions are not likely to specifically mention the game.  Maybe publication titles should be searchable,?

**Comment by meshuggahtas** [comment]
This issue:
- The submission is shown because it includes the whole word **Tomba** while the publication doesn't
- The publication only includes **Tomba!**in 1 place: Game. Which the search found. 

My comment from the closed issue https://github.com/TASVideos/tasvideos/issues/834 with similar problems:

Since I'm just a contributor and I don't know how these wiki stuffs gets talked about, I leave me notes here:
- **megaman** and **Megaman** won't give the exact same results. It will be definitely in different orders, and I think they don't result in the same amount of hits

Example:
https://tasvideos.org/Search?SearchTerms=megaman - Wiki and post results
https://tasvideos.org/Search?SearchTerms=Megaman - Wiki and post results in different order

- There is definitely a bug in what strings get's evaulated as matching. Sometimes it matches a game's name, sometimes it matches a part of a game's name and sometimes it won't show it.

Example:
https://tasvideos.org/Search?SearchTerms=banned shows GBC - Pokémon: Platinum Edition because the name is Kou Dai Yao Guai - Bai Jin **Ban** (ned) edit: the first 3 letters **BAN** of the search term **BANNED** got matches
https://tasvideos.org/Search?SearchTerms=jin+ba shows nothing, 0 results albeit has all the parts except missing 1 letter
https://tasvideos.org/Search?SearchTerms=jin+ban shows many results

- Results are not sorted. There should be a consistent sorting based on matching percentage of search terms. 
Example: 
https://tasvideos.org/Search?SearchTerms=activity - The results are a mixture of activity, activated, activivating and active with no order. 

- Results order can change. If you search the same thing, it won't be on the same page everytime.

Example:
Open link in different tabs and see the difference
https://tasvideos.org/Search?SearchTerms=activity

**Comment by meshuggahtas** [comment]
Notice how searching for:
- banned returns ban 
- jin ban returns jin ban
- jin ba not returning jin ban
- tomba not returning tomba!

**Comment by vadosnaprimer** [comment]
Movie/submission/wiki page titles should absolutely be searchable IMO.
