### ISSUE TITLE
Support compressed files for user files

### ISSUE THREAD

**Issue by Fortranm** [TASVideos/tasvideos#1057]
I tried to upload a .dsm file with size of 25.7MB and got "413 Request Entity Too Large".

**Comment by Masterjun3** [comment]
How much free space do you have? https://tasvideos.org/Profile/UserFiles
If you have less than 25.7MB free space, then this is by design, due to an unreasonable assumption:
https://github.com/TASVideos/tasvideos/blob/68197966810bc5209db2326ad6a4379b88aeb381/TASVideos/Pages/UserFiles/Upload.cshtml.cs#L84-L86
Just want to check if that's the issue you're running into here, or if this is a different one.

**Comment by adelikat** [comment]
it's a setting at the nginx level, not the code

**Comment by adelikat** [comment]
excuse me, actually it is a kestral limit that could be upped with code, if we can figure out how, and nginx is simply set to match, since any higher would just hit that limit

**Comment by nattthebear** [comment]
We could also chunk upload on the JS side

**Comment by adelikat** [comment]
Is is possible to gzip before uploading on the JS side?

**Comment by nattthebear** [comment]
Yes, certainly.

**Comment by nattthebear** [comment]
851254db3e8dfee88f60fee07d8142ce8ba6bf56
