### ISSUE TITLE
Do not use misleading breadcrumb visual style in forums

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1086]
![image](https://user-images.githubusercontent.com/22375320/152944324-90689c5b-a7b9-435b-8fd1-aa3ba3d6a8b2.png)
This page visually tells people the page link is https://tasvideos.org/EncodingGuide/Logo

But on the forum
![image](https://user-images.githubusercontent.com/22375320/152944450-badb3145-e42b-460a-ba55-01d36ce716d5.png)
it now looks like this can be reached by https://tasvideos.org/Forum/BizHawk/BugReporting
But this isn't the case.

When adding breadcrumbs I intentionally didn't add it on the forums for this reason.
The forum navigation used to be next to the title box, and used → for separation, so
```
Forum → BizHawk
[Bug Reporting]
```

**Comment by vadosnaprimer** [comment]
While it may be misleading in terms of effective URL, I think this is too neat to change. After all you mostly actually use this thing for quick navigation. If you want to see the URL, you look at the URL bar.

**Comment by vadosnaprimer** [comment]
That looks great!

**Comment by TiKevin83** [comment]
I'm not opposed to the arrow instead of slash style but I'd want to implement as an override of whatever bootstrap does so we retain consistency around their breadcrumb model

**Comment by Masterjun3** [comment]
Couldn't you just overwrite `--bs-breadcrumb-divider` on forum pages?

**Comment by Masterjun3** [comment]
> adelikat: the site urls are very navigatable just from typing.  I'm a big believer that the url bar is a UI, not a mystical box of magic

I would say some end users do care about difference in URL design. And teaching users this by having a different breadcrumb design is a simple and intuitive solution.
@TiKevin83 What is the downside from using a different divider?

**Comment by TiKevin83** [comment]
The PR worked towards handling stylistic consistency in headings. If we want to root cause the consistency issue here, we could work to restructure forum URLs to be semantic instead of building the inconsistency into the page UI. I'm also wary of anything where we override styles on the forum as a general concept because of the old site. We could band-aid it with the arrows but my gut feel is that more people would just notice "huh that's different" than realize "oh the url bar doesn't match the breadcrumb on these pages"

**Comment by adelikat** [comment]
I agree with masterjun, use slashes when it does represent the url, using the -> arrow thingy when it doesn't
