### ISSUE TITLE
Hide sensitive data until requested

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1095]
Currently, if someone has according permissions they will be able to directly see sensitive data like e.g. the Email address on user profiles.
This data is displayed without warning, without a prompt, without a subpage, directly on the front profile of a user.

The scenario I'm imagining here is someone with these permissions live streaming or sharing their screen, and clicking on a harmless looking user profile link, and so either accidentally leaking data or being led to leaking data of a certain user by a malicious third party.

Modern sites usually hide sensitive data until there is an explicit request on a page to show the data, like a button or a toggle.

**Comment by Masterjun3** [comment]
And I personally just don't want to always have people's data in my face, so please put it somewhere I won't keep accidentally seeing.

**Comment by meshuggahtas** [comment]
List of Personally Identifiable information (Note: Public user information shared by the user are not taken into account):
- Email Address
- IP Address

My suggestion: mask them completely or at least partially and interact with these values through the existing system. This might require a few lines of codes, I can't really assume the work+time of this.

My not complete idea: 
- Change the display value of email addresses and IP addresses become ***.***.***.*** and ******@********.** or only ***************. 
- Send e-mail as they would gain e-mail notification from a thread for example, not by copy-pasting their email address
- Banning IP... this is a bit more complex scenario because an attacker might not registered to the site needs to be hunted down, which requires multiple IPs being comparable. I need to think more thoroughly 
- If you need the exact value, rely on the database (should be not used in the future to obey the "mask completely" part)

In the future, in another ticket, if there are multiple staff users able to interact with the Database, tables with these two Personally Identifiable Information and some others should be restricted and be logged to increase the security of sensitive data for both the users and staff.
