### ISSUE TITLE
Latest publications table on homepage takes up more space due to line breaks in date cells

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#1112]
v2.3.21:
![Screenshot_20220221_030227](https://user-images.githubusercontent.com/13409956/154854613-c8c51627-bf50-4e62-9932-2c2aecc81ca0.png)
I suggest using `&nbsp;`. Here's what it looks like after replacing the spaces in the first date (column 1, row 2) with `&nbsp;`:
![Screenshot_20220221_025648](https://user-images.githubusercontent.com/13409956/154854630-7fafba9c-6306-4b73-be81-22926c6fb17e.png)
Might want to replace the space in "(Was xx:xx.xx)" too to keep that together on the second line.

**Comment by Masterjun3** [comment]
Instead of using `&nbsp;` it would probably be better to use the css property white-space nowrap. The date display is used in a lot of different places where breaks can be needed. Speaking of that.
While this suggestion can look good on big screens, the white space breaking is much more necessary on mobile widths or in general when you don't have a lot of space for the columns.
The reason it looks off here is because of the very large space taken to display all the authors for the row of CELESTE Classic. The calculations for distributing column widths is skewed in favor of the author column.

So all in all, I think an argument could be made about displaying this data in html tables being a bad choice for the modern web. But I don't think the suggested solution to prevent wrapping the date column is improving the situation and only adds edge cases where space is distributed unnaturally.

**Comment by Masterjun3** [comment]
Fixed, by redesigning the whole thing in #1514 .

**Comment by YoshiRulz** [comment]
May still be an issue with the userfiles table.
