### ISSUE TITLE
Forum search options

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1191]
My job on the site has been to remember the past as a reference, to ensure that we're doing things consistently, and if we find out we were doing things wrong, I'd be there to provide examples of how we were doing it wrong and why.

This means I used to search on forum **A LOT**. Most of the time it was a certain phrase that I remembered for many years or a certain user who said something very meaningful (sometimes me). In some cases it's helpful to only show threads where the needed text appears, to avoid displaying every post, checking every post, and making sure they are from the same thread.

So there are a few search options I'd like to have that were very useful on the old site:
- Search forum only (would probably also save on site load when it searches through wiki that I don't need)
- - Ideally there would be options to search different areas on the site, like forum, wiki, movies, submissions, games.
- Search in posts by a certain user
- Don't ignore words in a query that's surrounded with quotes, and don't ignore letters in those words (example where it only actually searches for `bounds` (sometimes dropping the `s` for good measure) while I need the whole phrase https://tasvideos.org/Search?SearchTerms=%22out+of+bounds%22)
- Display result as threads instead of posts

**Comment by meshuggahtas** [comment]
1 - Ability to select where to search: Currently Games, Wiki and Forum present. Good idea to expand it with and select between movies, submissions and userfiles.

2 - Ability to search post by a user: While there is https://tasvideos.org/Forum/Posts/User/MESHUGGAH which can be expanded (clicking page 1) to get https://tasvideos.org/Forum/Posts/User/MESHUGGAH?CurrentPage=1&PageSize=25&Sort=-CreateTimestamp we still need to change PageSize to the number of users' post to get all in a single page to make a CTRL+F, which would be very cumbersome for users to search within a wall of text.

My personal suggestion would be: Scenarios where multiple pages can be used to start, should be both updated. 
- Searching for a post both at Search and the link from 2. 
- Searching for movie both at Search and at publications
- Searching for a userfile both at Search and at UserFiles page etc...

3. Searching with quotes: I've tried multiple ways, out&of&bounds out&&of&&bounds "out of bounds" out+of+bounds but no luck with getting only the exact phrase. I don't know what would be the correct way, because that postgres document is not made for humans.

4. Display results of forum posts as thread - and only list it once. If there is a discussion about "super Mario 720", all those post should appear as a single thread.

**Comment by vadosnaprimer** [comment]
> we still need to change PageSize to the number of users' post to get all in a single page to make a CTRL+F, which would be very cumbersome for users to search within a wall of text.

Yeah, I have 10k posts, I bet nobody wants me to put them all on the same page in order to search through them :D

**Comment by adelikat** [comment]
When I see big blocks of things and then posts with more big blocks of things that are miscellanous problems with varying degrees of effort, I tune out.  Sorry but tickets like this don't get resolved, they just linger for years.  Please break up your needs into individual tasks that can be easily implemented
