### ISSUE TITLE
Profile splits when author and forum names don't match

### ISSUE THREAD

**Issue by coolkirby2000** [TASVideos/tasvideos#1274]
At the time of writing, the [latest publication](https://tasvideos.org/4668M) is by [benstephens56](https://tasvideos.org/Users/Profile/benstephens56), who goes by [benstephens1000](https://tasvideos.org/Users/Profile/benstephens1000) on the forum. This splits his relevant data into two profiles:
* benstephens1000 contains his post count, avatar, preferred pronouns, last login date, wiki edit count, submission count and movies rated, among other things.
* benstephens56 contains default data for everything except his single publication and submission (the latter being the only link to the other page), and player points.

This may affect other users who use two different names, now and in the future. Ideally, we should either combine the two automatically, or avoid the bug by requiring users to submit with the same name they use on the forums. Or maybe we can have one redirect to the other, since they share submission data at least.

**Comment by SamsaraTAS** [comment]
This had to have been a manual author name edit, in which case the best solution would be to prevent submitters from editing their own names on their submissions.

**Comment by Masterjun3** [comment]
There is actually nothing wrong here.
There was no "profile split".

Both of these accounts were created in 2016. And for the sake of argument since they're two different accounts let's say they're two different people.
One submitted a movie and set the author to the other one. There is explicit code that makes sure this is allowed. And now this movie was published.

Now of course, let's say the reasonable assumption by @coolkirby2000 that "[benstephens56](https://tasvideos.org/Users/Profile/benstephens56), who goes by [benstephens1000](https://tasvideos.org/Users/Profile/benstephens1000)" is correct, so they are two accounts of the same person, then ideally this quirk would have been caught before publication and handled there.

For now, after confirming with the user that both accounts are theirs, all we have to do is change the author of the submission and publication, remove the unused account, maybe rename the true account properly this time, and maybe reencode to reflect the username change.

**Comment by adelikat** [comment]
Closing this ticket since there is not code development action item here.  We may want to combine those accounts if they are indeed the same but that isn't a code change.
