### ISSUE TITLE
Game pages without a screenshot specified fail to take screenshot from publication

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#1319]
I swear what used to be the case was that if a game page didn't have a url listed in the screenshot url field, it would take one from the publication. However for https://tasvideos.org/1092G this fails to be the case
![image](https://user-images.githubusercontent.com/6119096/171392429-39673ee1-941d-48a8-b7a3-adf8bd45a019.png)

The image being linked is https://tasvideos.org/~/media/2627M.png when it should be https://tasvideos.org/media/2627M.png

**Comment by GlenCarpenter** [comment]
Hi there, this seems pretty simple.  Is this an issue with the URL for static files?  I'd be happy to look into it.

**Comment by Masterjun3** [comment]
The reason this happens is actually because of commit https://github.com/TASVideos/tasvideos/commit/b2a0a958da43854982d7fd49266a2bef3b8f15f8 .
Usually in razor code the tilde would be automatically replaced by the root, but since it's a string there it isn't replaced.
Undoing the commit would solve this issue, but you might want to ask @adelikat .

**Comment by adelikat** [comment]
This is a subtle issue in razor then.  ~ is an html feature not a razor.

**Comment by YoshiRulz** [comment]
It is not part of HTML or related web specs. (Unix servers have long allowed literal '~' in `/~<username>`.) It's [an ASP.NET feature](https://learn.microsoft.com/en-us/aspnet/web-pages/overview/getting-started/introducing-razor-syntax-c#referencing-the-virtual-root-the--operator-and-href-method), at one point called the "Web application root operator".
