### ISSUE TITLE
[F.Rq.] API/search: Add 'Offset' field

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/tasvideos#1621]
In many aspects of site searching, you can see multiple pages of search results. For instance, for new publications, there's `https://tasvideos.org/NewMovies`; going to the next page of results will take you to `https://tasvideos.org/NewMovies?CurrentPage=2&PageSize=25`

However, this URL isn't particularly stable. Any time a new publication happens, the second page of results will shift. For certain use cases this is inconvenient, like getting publications published after a certain publication. `StartYear` and `EndYear` sort of exist for this purpose, but they aren't granular enough.

One solution I've seen on this other sites it add something like an `Offset` field that contains the relevant publication id (or for other searches, the submission id, game id, etc.). Obviously, records may get deleted occasionally, which would render search results non-identical, but this kind of filtering would still be useful.

**Comment by adelikat** [comment]
I don't intend to rewrite how paging works.

the actual api https://tasvideos.org/api/index.html uses offset, your example are web pages that utilize paging.  I think for these types of pages, current page and page size is a standard and good way to implement this.  At the very least, changing to an offset is not objectively better.

Also, the example is curious since the intended use would be for new movies, so I'm not sure why you would want some kind of static link to a specific set of publications in the context of seeing new content
