### ISSUE TITLE
External links should open in a separate tab

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1679]
In general, sites on the web are made to open in a new tab if they lead to a different domain.
We currently open these links in the same tab. We should make them open in a different tab.

We also currently use this specific icon. It is *the* icon to tell users it will open in a different tab.
![image](https://github.com/TASVideos/tasvideos/assets/22375320/8910601b-37fa-4e4f-b24e-817d5939b9c4)
(Meaning even if we don't want to open in a different tab for some reason, at least that icon then needs to change.)

**Comment by RetroEdit** [comment]
I'd personally prefer to have a choice on where links open. In most web browsers, it's easy enough to open links in a new tab by using Ctrl+click, middle click, or right-clicking and then selecting `Open Link in New Tab`.

That icon does not universally signify links will open in a new tab. Wikipedia uses a similar icon, and the links do not open in a new tab by default.

**Comment by moozooh** [comment]
I think this should depend on the user agent. For PC browsers, this is completely a non-issue because middle-click and ctrl-click exist, so, at least in theory, there should never be a situation when a user would _prefer_ forfeiting the option to choose whether they want to stay on the current tab when opening a link.

Mobile devices are a different story, however, as their simplified, stripped-down interface encourages a different UX. So I could very well see it being appropriate and even welcome in that case. But not on PC.

**Comment by Masterjun3** [comment]
It seems the suggestion by me is unwanted, so I'm closing my issue.

**Comment by YoshiRulz** [comment]
If you're on ~~mobile~~ Android and a link opens in the current tab, it's super easy to hit Back, long-press, "Open in new tab". Arguably easier than doing the same with a mouse on desktop.
