### ISSUE TITLE
Posts moved to restricted subforum are still shown as most recent for their original subforum

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#1696]
Both "Last Post" and the unread badge are wrong.

Found during circumstances of #1694.

"Mark all Posts as read" on the General subforum didn't work, but the global one did work.

**Comment by adelikat** [comment]
This is just the fallout from a failed attempt to remove the topic from a spam operation

**Comment by SamsaraTAS** [comment]
This is still happening with the spam button.

**Comment by Masterjun3** [comment]
The issue is our denormalization with our post<->subforum relation.
When pressing the spam button, we only set the new topic of the post as seen below. But we also need to set the *subforum* of the post.
https://github.com/TASVideos/tasvideos/blob/6c29e17e2ca5c97680053abb749596846e4ffb86/TASVideos/Pages/Forum/Posts/Edit.cshtml.cs#L279
