### ISSUE TITLE
Going back to the submission form page only restores the first author

### ISSUE THREAD

**Issue by g0goTAS** [TASVideos/tasvideos#1716]
https://www.youtube.com/watch?v=P1tc8qjS7LU

**Comment by Masterjun3** [comment]
This is browser behavior we can't affect. We don't actually support restoration of fields.
More importantly, a page _is not allowed to be cached_ if there's a submittable form on it, because of [antiforgery](https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0) stuff.

We currently have a manual restoration feature for submission texts and posts and so on, but not for other fields.
Closing this as wontfix.
