### ISSUE TITLE
Welcome banner is likely to be ignored

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#1816]
https://en.wikipedia.org/wiki/Banner_blindness

Suggestion: A concise message in a large font which makes it clear that the banner is for new users, and not a news item or an advertisement. Something like:
![Screenshot from 2024-04-28 01-15-04](https://github.com/TASVideos/tasvideos/assets/13409956/a2db4b63-79ae-4292-bd11-b48f815e409c)

**Comment by Masterjun3** [comment]
I can agree with this. And since the welcome text is just a wiki article, I have implemented your suggestion: https://tasvideos.org/Wiki/PageHistory?path=System%2FWelcomeText&fromRevision=13&toRevision=14

Check https://tasvideos.org/ in a private window to see it. It looks just like in your image. :D
