### ISSUE TITLE
All Youtube Embeds are blocked

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1852]
All YouTube embeds show "Blocked Page".

In firefox, the request is cancelled with a "NS_ERROR_DOM_COEP_FAILED" error, which means
> Used to indicate that a resource load was blocked because of the Cross-Origin-Embedder-Policy response header

Example:
![image](https://github.com/TASVideos/tasvideos/assets/22375320/a68aba3d-7221-46c8-ac52-cfd2f1e3d24e)

**Comment by YoshiRulz** [comment]
This is happening because, despite what [Google's own documentation](https://web.dev/articles/coop-coep#:~:text=a%20new%20COEP%20%22credentialless%22%20mode%20that%20allows%20loading%20resources%20without%20the%20CORP%20header%20by%20stripping%20all%20their%20credentials) says, `Cross-Origin-Embedder-Policy` *does* require buy-in from third-parties just like CORS before it, at least for `<iframe/>`s.
The "intended" solution is for [YouTube to set its header](https://issuetracker.google.com/issues/240387105). Don't hold your breath.
There is a fix for Chrome—[`<iframe credentialless/>`](https://developer.mozilla.org/en-US/docs/Web/Security/IFrame_credentialless) or maybe `<iframe allow="cross-origin-isolated"/>`—but to cover older Chrome and other browsers, we'll have to relax the COEP header to `unsafe-none`, which is the most lax. It's also the default, but I think the header should be set explicitly.
