### ISSUE TITLE
Rearrange global tabs

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#193]
Now that we have dropdowns in navbar, it's a brilliant opportunity to rearrange the incredible mess it has become.

Some insight on user visit stats would be very nice. Also we should go through all the current tabs and assign some kind of a priority value to them, also decide on the hierarchy what should depend on what. Then using this data will make it easy to build a navbar that only has thing we actually need, and all the things it won't have will be linked from accessible places.

**Comment by meshuggahtas** [comment]
Insight on visitors wouldrequire **web analytics** that might be not GDPR compliant, which would also bring some other legal tasks to do. I'm not sure about the legal side of collecting anonymous user data in order to improve their experience of using the website, but I would suggest using one. I don't have software suggestion at the moment.

Regarding the menus. New one:
![menu1](https://user-images.githubusercontent.com/31288337/145491196-f5533672-c3ab-47d2-8078-a94897bc8f9a.PNG)
Legacy one:
![menu2](https://user-images.githubusercontent.com/31288337/145491207-706472fa-d075-4cc0-886f-4e7c232431b6.PNG)

**Comment by meshuggahtas** [comment]
Is this issue still relevant? 
- The global tabs have been changed.
- We didn't added priority value
- User stats insight (web analytics) is not decided I guess?

**Comment by TiKevin83** [comment]
oh hey yeah I fixed this already

**Comment by meshuggahtas** [comment]
Personally I don't like the current structure but I'm unsure why, so I try the weighting/priority thing. There are pages that different users use at different frequency. This post tries to cater around that. Not reopening issue as it's personal.

**Current navbar** (The name of the navbar link - The dropdown links - Number of / type of visitors to use that link)
**Home** - any - OK
**Movies** - pubs, subs, userfiles - any - OK
**Forum** - any - Should be lower
**Chat** - any - Should be lower
**Articles** - index, game, emu - Should be higher
**Staff** - 25 "staff member" + ~55 editors - Is it neccessary to have this alone instead of inside About as dropdown link? If Articles has ArticleIndex, this should be done here too
**About** - any - Seems odd to place it here
**Admin** - 4 links - 25 "staff member" + ~55 editors - OK
**Wiki** - 5 links - 25 "staff member" + ~55 editors - OK
**DarkLight** - dark light auto - any - OK
