### ISSUE TITLE
Topic wrongly showing up as unread

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/tasvideos#2007]
I've sporadically noticed issues with the unread posts system, but this is a discrete one that's been persistently happening at the moment:

When I navigate into the [Published Movies subforum](https://tasvideos.org/Forum/Subforum/16) and visit the current most recent topic, [#9257: Sand's GB Kwirk "Heading Out?" in 25:15.19](https://tasvideos.org/Forum/Topics/25645), the unread post icon still shows up when loading the published movies subforum again. Hitting the unread post icon itself takes me to [this post](https://tasvideos.org/Forum/Posts/532011), but the topic still shows up as unread.

`Mark all posts as unread` probably would solve this, but I figure I'd bring this up so the underlying issue could hopefully be fixed.

**Comment by YoshiRulz** [comment]
Repro'd (and with the next most recent topic in that subforum, but no others).

**Comment by Masterjun3** [comment]
Oh yeah, I think I understand why this bug happens.
For performance reasons, the server only pre-calculate all posts that are posted in the past 14 days as "activity posts", and lets the client browser do the work of marking them as seen or not.

However, the server also caches the pre-calculated posts, so that posts 15 days or older are still marked as an "activity post". The browser however doesn't mark them as seen, because they're older than 14 days.

Previously, this didn't happen as frequently because we deployed new code like every week, which refreshes the caches.
But this is indeed a bug, I just don't know how to fix it yet.
