### ISSUE TITLE
Set rich author metadata on sent emails

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#2025]
Seeing emails from "noreply" in your inbox is not helpful.
I imagine this is as simple as adding 1 header, but I don't know OTOH. edit: I think it's literally just `From: Name <name@domain>` which is currently set to `noreply <tasvideoagent@tasvideos.org>` :P

Unrelated, I think DKIM is misconfigured? `Authentication-Results: dkim=none [...]`

**Comment by Masterjun3** [comment]
We currently send emails with the name set to "noreply" and the address of tasvideoagent at tasvideos (dot org).
I agree that we should change the name to "TASVideos", because every email provider uses that field to merge mails, show a profile picture, and all that. The "noreply" isn't good there.

If we absolutely need a "noreply", then it should go in front of the @ in the email address. This is what other websites do when they have a noreply email.
