### ISSUE TITLE
Create a Bluesky Distributor.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#2041]
Well [might as well use that account](https://bsky.app/profile/tasvideos.bsky.social) that @SamsaraTAS is squatting on to good use eh?
Also mainly making the issue request because this is something that's talked about a few times, but with no real action being done, so it's more of a goal thing or whatever.

I'm just listing like the needs:
- Submissions
- Publications
- News Feed Posts

[Basically what the Twitter integration had I guess](https://github.com/TASVideos/tasvideos/commit/e68a736e86ce319fee58315ae277ac38a6cd58e9).

Probably the major one to point out for when this process is being done is to change the handle to point to the website instead of a bsky account.

**Comment by Masterjun3** [comment]
Ah yes, I've looked at this in case we ever want to do this:
- There is a [Bluesky HTTP API](https://docs.bsky.app/docs/category/http-reference) for creating posts, which makes this possible. The API can do a lot more, but we don't need more.
- Bluesky supports App Passwords, so we can use one for the site, and the main account holder can stay in manual control of the account.

The account's handle is currently `@tasvideos.bsky.social` which is fine.
We have an option to convert an account into an "official account" with our domain. It would then appear as `@tasvideos.org`. We can do this at any time later if we feel like it. We won't lose any posts, and followers don't have to refollow.
To do this we have to set a certain txt record in our domain registrar, so that Bluesky can verify we own the domain.
(Docs for changing the domain in this [Bluesky blog article](https://bsky.social/about/blog/4-28-2023-domain-handle-tutorial) and in the [AT Protocol Identity Guide](https://atproto.com/guides/identity).)
But the domain thing is completely optional anyway.

**Comment by adelikat** [comment]
This has been done
