### ISSUE TITLE
Redocument the displaymovie module, and fix references

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#285]
The module was changed to have the same functionality as the Movies list pages.  Documentation needs to be fixed to match the new functionality.

In addition, a few breaking changes occurred, 

1) /HomePages/alden/Exhibitions/BestSellingGames that utilizes the name feature.  Instead of name, it will need to be either the Game Id or the Game Group Id as a replacement
2) /HomePages/NitroGenesis utilizes player=449,519, the new param name is author and the ids will have to be fixed to be the user id, as opposed to the player id which no longer exists in the new system

**Comment by bigbass1997** [comment]
Where should this get documented?

I've noticed that the `flags` token filter has been changed to `flag`, and the values used seem to be case-sensitive (so `flag=Verified` no longer works, but `flag=verified` does). Similarly `flag=FastestCompletion` doesn't appear to work anymore, but neither does `flag=fastestcompletion`.

**Comment by adelikat** [comment]
The documentation goes here: https://tasvideos.org/TextFormattingRules/ListOfModules

fastestcompletion is no longer a flag, these are the flags currently:
commentary
newcomerrec
atlas
knownrecords
firstplatform
verified
improve

**Comment by vadosnaprimer** [comment]
fastestcompletion is a very important flag and a ton of effort was put into setting it. It's the only way to tell which branch is actually any%, because blank branch doesn't work for that indication. It's also a way to mark movies that are unconditionally acceptable to Standard.

**Comment by bigbass1997** [comment]
This page is entirely broken due to the removed fastest completion flag https://tasvideos.org/FastestCompletion/Negative. I don't know how much usage that page has, but it's something I noticed while searching for broken pages. I also don't know if it's even possible to negate flag parameters anymore either (like what's used on that page).

**Comment by vadosnaprimer** [comment]
Yeah having NOT on flags is also very useful when compiling lists, because you check which movies need the flag but don't have it. That particular list was very hard to compile (to flag all the movies that need it) because there was no option to use NOT on tags, which would also be incredibly useful to have.

**Comment by adelikat** [comment]
Let's hold off on documenting this until I fix the fact that tokens need to be lowercase, that wasn't intended

**Comment by adelikat** [comment]
Closing this.  The parameters I want to support have been added, links have been fixed, and docs have been updated
