### ISSUE TITLE
Infrastructure: Multiple instances and Load Balancer

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#415]
This is one of the consequences of a compiled language.  Updating the site takes downtime as opposed to php.

I think a hard requirement of the new site is to elminate or greatly minimize this downtime.  The code is designed for multi-instance.  We should set up up the following system:
- 2 instances running concurrently
- nginx as a reverse proxy and load balancer
- A deployment script that takes each one down, updates, and starts it back up, one at a time to eliminate downtime

**Comment by Invariel** [comment]
Alternately, we can build the site and move it into a static location so that nginx entirely is serving pages without using Kestrel in the middle.  The problem with this approach is that our CSS is compiled and kept in memory instead of being written out to files.

The advantage of this is that we can build the site in the background and then casually overwrite files as necessary (or wholesale) without bringing the site down.

**Comment by adelikat** [comment]
Closing this ticket.  We have a good process now with a version controlled service shell script that minimizes downtime.  Eventually we can run multiple instances behind a load balancer to potentially eliminate downtime, but we can put that off to the future, and by then, it is best to write a new ticket for the specific tech we intend to use
