### ISSUE TITLE
Add !!!! headers to the TOC

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#50]
Sometimes 3 kinds of headers is just not enough, so we add 4th, and it only makes navigation harder if it's absent from the TOC.

**Comment by nattthebear** [comment]
Pages have a single `<h1>` on them already; the title of the page.  Since there's no way to emit `<section>`s with wiki markup, there's no legal way for additional `<h1>`s to make any sense.  The only reason we can emit them is legacy compatibility; better for something to happen than the page to not work at all.  But for editing new content, `<h1>` in page content is a hack that should not be used.

I am suspicious of the claim that a wiki page needs that many levels of outline.  Sounds like you'd be better off splitting content into separate pages at that point.  But if you're dead set on this, we'll need a syntax for `<h5>`.

**Comment by vadosnaprimer** [comment]
The current wiki uses such headers. Sometimes it's just a stylistic choice (because such headers look so different)) http://tasvideos.org/Platforms.html
but sometimes it's necessity http://tasvideos.org/MovieRules.html

It's not always possible or sensible to split such things into separate pages. And in some cases the amount of headers used just can't be lowered without losing some of the page's organization.

**Comment by nattthebear** [comment]
That page is way too long and near unreadable garbage.  Not that it matters; if you want an `<h5>`, you'll get an `<h5>`.  But not an `<h1>`.

**Comment by vadosnaprimer** [comment]
I like special treatment for h2! It just seems wiki headers will correspond to those differently: !!!! = h2, !!! = h3, etc.

**Comment by nattthebear** [comment]
That would break every page that properly uses !!! as its biggest heading to indicate h2

**Comment by vadosnaprimer** [comment]
So was the idea to have 2 versions of h2? Or to shift the other headers down and insert !!!! as the second one? Either way I don't see how it'd break the existing usage of them. Can you show an example?

**Comment by nattthebear** [comment]
Maybe I've misunderstood what you're trying to do?  Normal page markup looks like this:

```
!!! Big Stuff
!! Some More Stuff
! Stuff
! Stuff
!! Some More Stuff
! Stuff
!!! Other Big Stuff
!! Some More Stuff
! Stuff
! Stuff
!! Some More Stuff
! Stuff
! Stuff
!! Some More Stuff
! Stuff
! Stuff
```

For a case like this, we need to assign `<h2>` to the `!!!`, `<h3>` to the `!!`, and `<h4>` to the `!`. `!!!!` is not `<h2>`.

**Comment by vadosnaprimer** [comment]
I'm just following adelikat's suggestion here, which I love:
https://github.com/adelikat/tasvideos/issues/50#issuecomment-395167250

**Comment by nattthebear** [comment]
I think he was suggesting that we give H2s more impactful styling in all cases.  I think that would be fine.

**Comment by vadosnaprimer** [comment]
I interpreted it as
```
h1 - page title
h2 - !!!! custom header identical to page title
h3 - !!! usual header
h4 - !! usual header
h5 - ! usual header
```
Is this feasible?

**Comment by nattthebear** [comment]
It would be breaking 99.9% of good pages (that don't use `!!!!`) for 0.1% of shit pages (that do use `!!!!`)

**Comment by vadosnaprimer** [comment]
I don't understand how it would break them.

**Comment by nattthebear** [comment]
They'd go right from <h1> to <h3>.  The whole point of this is to have outlines that make sense and work with screen readers and accessibility tools; if we don't need that; just make everything a `<b size=large>`...

**Comment by nattthebear** [comment]
Even leaving out accessibility, this would also be a breaker for normal users on normal pages due to styling.  Most pages would now have a "gap" where they go right from the single automatically generated page title <h1> to a much weaker looking <h3>, where as a small number of incomprehensibly overloaded pages would be the only ones properly styled

**Comment by adelikat** [comment]
I want to close this ticket.  I think I agree with @nattthebear that pages that use !!!! are misbehaving, it should be avoided unless absolutely necessary, and in those rare cases, there is also a TOC? sounds like a page that needs to be rethought rather than supported at the expense of the 99%.

I would be open to the idea of !!! generating a header that has some kind of styling, underlined to a different color, etc, and we can discuss that, but should be a dedicated ticket and discussion.

I'll close this in a few days if I do not here any dissenting opinions

**Comment by vadosnaprimer** [comment]
Ye the initial request was probably caused by being limited to just 3 header types, which is not enough if we have to be elaborate. `!!!!` was just a workaround.
