### ISSUE TITLE
Feature Request: Prevent author from rating their own movie

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/tasvideos#503]

**Comment by meshuggahtas** [comment]
TODO: Link tasvideos discussion thread relevant to this

This feature needs to be discussed before implementing.

Imagine the following two usually occurring situation:
1. Single author movie rating their own movie
- Author creates TAS
- Author watches own TAS
- Author expresses own feelings of own movie

2. Multiple author movie rating their own movie
- Authors creates TAS
- Authors watches their own TAS
- Authors expresses own feelings of own movie

The only situation where this can be abuse, is when Author(s) desperately rate objectively to gain more player points instead of subjectively expressing their own feelings, which also changes their own player points.

My suggestion is:
- Let author(s) to rate their own movies
- Calculate rating and player points with a weight to reduce the impact of point change while allowing them to express their own feelings

**Comment by vadosnaprimer** [comment]
If ratings are used as personal favorite, your own movie may be your personal favorite but you won't be able to have it in your list. Allowing authors to rate and then reducing weight of their vote is a better approach imo.

**Comment by MemoryTAS** [comment]
The rating guidelines say "Because of the obvious bias, you should not rate your own movies." Currently self-rates don't directly impact player points, but it does affect the total number of ratings.

**Comment by adelikat** [comment]
Just want to point out that the user's rating is not factored into the average rating, and therefore not into player points.  Given that, do we still want to bother preventing it?

**Comment by vadosnaprimer** [comment]
If it's harmless I see no reason to block it.

**Comment by adelikat** [comment]
Closing, since it is deemed harmless
