### ISSUE TITLE
Publication view: replace torrent links with direct links

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#646]
![изображение](https://user-images.githubusercontent.com/7092625/145250577-71853105-46f2-479d-add9-7d64efb0a116.png)

This thread reminds us why torrents as we use them right now are useless:
http://tasvideos.org/forum/viewtopic.php?t=22931

Direct links on the other hand are not useless and will be relevant for a good while. But the publication module only has torrent links and not direct download links.

**Comment by ThunderAxe31** [comment]
Just to give a bit more context: from looking at the source code of `_MovieModule.cshtml` it seems there is already a logic for including the direct urls to the available mirrors, but for some reason it's not working:
```
<a condition="@(!string.IsNullOrWhiteSpace(Model.MirrorSiteUrl))" href="@Model.MirrorSiteUrl" class="ms-2">A/V file via Mirror<br /></a>
```
Instead, the logic for showing the Torrent downloads is working, even though I think it should be removed (topic that feos linked) due to their uselessness:
```
<span condition="Model.TorrentLinks.Any()">
	@foreach (var torrent in Model.TorrentLinks)
	{
		<a href="~/torrent/@torrent.Path" class="ms-2">A/V file via BitTorrent @TorrentRemark(torrent.Path, torrent.Id)</a>
		<br />
	}
</span>
```

**Comment by Masterjun3** [comment]
I'm not even sure what the purpose of a MirrorSiteUrl even is (It's not multiple, only a single string). Submissions also have a MirrorSiteUrl field and it gets transferred to the Publication on publishing. It's next to the submission Online-watching URL, so I suppose it's for secondary streaming encodes, but the publication OnlineWatchingUrls exists for that purpose.

The actual direct download links are in a different database table called PublicationUrls.
