### ISSUE TITLE
Fill in Emulator info on Submisisons/Publications

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#648]
This isn't a developer ticket, but this is the best place we have to log todos.

We need to go back and fill in missing Emulator values for Submisisons and Publications.  A query can be made, or even a wiki module, to show those that are missing.  It doesn't have to be the emulator used, as long as it is an emulator version that syncs.

**Comment by meshuggahtas** [comment]
Tasks elaborated:

1. Gather the list of submissions and publications (all movies except UserFiles) without emulator info: Requires a SQL query or wiki module

2. Analyze and verify emulator info: 
- There's more than 14 potential different emulators used for syncing the movie.
- Emulators usually have multiple versions. 

Old movies (pre 2004) have higher the chances of the emulator used is the last version prior to it's date. Example: a NES movie from 2003 December probably uses FCEUX 0.97.5 released at 2003 November 12. These movies are probably lesser in quantity.

New movies (after 2004) have higher the chances of the emulator used is the most online widespread version of an emulator. Examples: FCEUX 2.1.0, 2.1.4, DeSMuMe 0.9.2. The reason is simply that larger projects can span through multiple years where changing emulator versions were not possible. These movies are probably greater in quantity.
- Prepare your emulator to run as fast as possible to reduce the time taken with watching the movie syncing: don't run other applications while testing, use turbo, disable performance limits.
- To verify syncing, publications have video encodes. Submissions usually have a temporary video encode. If you don't know how the ending should look like, google for a RTA speedrun equivalent of the movies' game and objectives.

Potential emulators:
http://tasvideos.org/EmulatorResources.html

**Comment by vadosnaprimer** [comment]
A whole lot of emulator versions were mentioned in submission texts, so if it's possible to automatically check them and suggest for human verification, that would probably speed up the process.

**Comment by meshuggahtas** [comment]
The only automatable (as in automation) process seems to be

Guessing emulator by ... and append results to filename before extension. This might speeds up the process of finding the right emulator with simple text/regexp based searches.
- **Movie extension**
- **Movie header**
- Submission text (can result false positive)
- Submission thread posts (can result false positive)
- ROM size (can result false positive)
- ROM extension (can result false positive)
- The original **date of submission**

Human interaction required for possessing the ROM, the emulator and verifying the TAS syncing.

**Comment by meshuggahtas** [comment]
An example of above suggestion:
- http://tasvideos.org/508S.html
- Filename Lagoon 1.08.33 OmnipotentEntity
- Extension **SMV**
- Header **SMV**
- Nothing relevant in submission text
- Nothing relevant in submission thread
- **2005-01-22**
- Google "snes" emulator 2005
- Found **Snes9x 1.43** after opening at least 6 pages of results

Aaaand... probably a bad idea to use this as an example because the TAS is more than 1 hour and I'm not sure my Snes9x 1.43 would be the right info for this TAS without attempting the possession part...

**Comment by SamsaraTAS** [comment]
This doesn't have to be an automated process. I don't really think it _can_ be, either, given the large number of submissions that withhold the proper information. I honestly think it'd be a lot easier to just build modules for this and #649  and crowdsource the information over time.

**Comment by meshuggahtas** [comment]
Made another stab at thoroughly thinking this out:
1. List of submissions:
- The API can be used, however there is a maximum number of PageSize query for submissions. Dump the results and share it to avoid unnecessary load on the server. Same approach can be done for https://github.com/TASVideos/tasvideos/issues/649
- Current URL for the API: https://staging.tasvideos.org/api/index.html
- The page has an auto-execution feature. If you click on try out, about 1 second after it will make an unnecessary performance load, no idea whats happening in the background. The order of filling values affects your time to complete the task.
Suggestions for creating your list with the API fields:
- **Title**: Has the ID and you can google the title to get the appropriate tasvideos site of the submission.
- **GameId**: Can be used for more information. Either use API or google.

- **Systems**: Focus on one platform at a time to reduce the number of potential emulators to try. 
- **RomName**: Which ROM you need to possess, at least this ROM is assumed to be used to sync for the submitter.
- **Frames**: Minimum estimated time required to test syncability.
- **MovieExtension**: Guessing emulator.
- **EmulatorVersion**: TODO: value if the emulator information missing.

- **Status**: You can use this information for priority. Published submissions and publications are more important than accepted, delayed, etc... ...canceled and rejected.

By the way, my example of finding emulator version for 508 seems to be right according to the API. Unsure if the information only present in the new tasvideos database, at least I didn't find this information on the legacy site.

**Comment by adelikat** [comment]
Probably easier to just make a wiki module and slap it on a page

**Comment by adelikat** [comment]
Closing, we have https://tasvideos.org/TODO/NoEmulator to track this work
