### ISSUE TITLE
Wii wrong frame count

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#671]
Submitting a published Wii TAS on the new site will show different frame count.

http://tasvideos.org/7210S.html 30108
Resubmitting it on new site 9680

**Comment by meshuggahtas** [comment]
Have no idea how to verify this. 
2:41.32 , would be around ~11k frames
30108 frame count, it would be ~8 minutes

**Comment by CasualPokePlayer** [comment]
The new site has to does some heuristics to obtain the "frame count" from a 60 FPS framerate by deriving it from the cycle count. This gives a framecount which has some semblance to time passed, and results in the correct time (give or take some time due to rounding, nothing major). Not wrong really, https://github.com/TASVideos/tasvideos/issues/309 would probably help this issue?
