### ISSUE TITLE
MSX wrong frame count

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#672]
Submitting a published MSX TAS on the new site will show different frame count.

http://tasvideos.org/5408S.html 20459
Resubmitting it on new site 20460

**Comment by CasualPokePlayer** [comment]
This is just the new site rounding up here when old site rounded down (another case of frame count derived from cycle count). I'd call this intended behavior here.

**Comment by CasualPokePlayer** [comment]
> CasualPokePlayer — Today at 10:59 AM
> @ adelikat i am considering it's consistent throughout parsers im going to guess rounding up in cases we're bullshitting a 
> frame count from cycle count is intended
> 
> adelikat — Today at 11:08 AM
> yeah, old site rounded down always it seems
> [11:08 AM]
> truncating

**Comment by adelikat** [comment]
Also, in the case that we are figuring out frames from cycle count, it makes sense to always round up.
Say for instance a movie's cycle count shows that it was completed in 99.5 frames.  Reporting 99 never makes sense.  But 99.5 doesn't either, better is to always round up and say it was a 100 frame movie.  This behavior is intentional in the new code.
