### ISSUE TITLE
Nickname from previous website version now appears as a separate contributor

### ISSUE THREAD

**Issue by 100thCoin** [TASVideos/tasvideos#734]
For my recent published TASs, since usernames cannot begin with a number, I have opted to write my username out as "OnehundredthCoin", and entered "100th_Coin" as the nickname field when submitting. Since the upgrade, my TAS now lists both "OnehundredthCoin" and "100th_Coin" as the creators.

https://tasvideos.org/4567M

**Comment by bigbass1997** [comment]
Hmm, API reports only one author for the pub: "OnehundredthCoin". The title may just be formatting the nickname wrong. In comparison, the submission's header text does properly display just the nickname.

**Comment by Masterjun3** [comment]
This was due to the old site only having strings as publication and submission titles, thus needing manual conversion. This was done and checked on the end of October 2021, so player entries that changed afterwards might be affected.

This doesn't need a fix in the code and instead a fix on the site. Both submissions and publications need to be fixed.

Here is a list of affected publications (and their submissions) I found back when I first noticed the problem:
- https://tasvideos.org/4548M
- https://tasvideos.org/4554M
- https://tasvideos.org/4558M

**Comment by vadosnaprimer** [comment]
Cleaned up those. What other movies need this?

**Comment by Masterjun3** [comment]
Their submissions need the change as well.

**Comment by adelikat** [comment]
Looks like submissions were fixed too, can this be closed?

**Comment by Masterjun3** [comment]
The submissions still aren't fixed heh.

**Comment by Masterjun3** [comment]
Here is what exactly to do to close this issue:
- https://tasvideos.org/7215S remove `Xindictive` from additional authors and add `New999` to authors
- https://tasvideos.org/7245S remove `100th_Coin` from additional authors and add `OnehundredthCoin` to authors
- https://tasvideos.org/7248S remove `Josh P` from additional authors and add `mxlenny94` to authors

**Comment by vadosnaprimer** [comment]
They changed their names after I fixed the publications. So where it was still wrong I did a blank edit for pubs so the right name is picked, and also I fixed the submissions.

**Comment by adelikat** [comment]
Closing this.  This conversation doesn't belong here, this is non-dev work.  If submissions/publication names are wrong, let's post in a topic (or the topic of the incorrect pub/sub) and have the conversation there
