### ISSUE TITLE
Add social links and other external usernames in post signature or under avatar

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#757]
Here is a non-exhaustive list:

- Link to TASVideos user page
- Link to YouTube channel
- Link to Twitter page
- Link to GitHub page
- Click to show Discord name
- Click to show Steam name

**Comment by TiKevin83** [comment]
How have we not thought of that before? Great idea

**Comment by YoshiRulz** [comment]
I'd have thought these would be on the profile, but that's probably a requirement for showing them on posts so w/e.

Having seen this overdone—one art community has **29 fields**—can I suggest limiting this to only platforms where TASVideos has a presence i.e. Discord, GitHub, and YouTube?

**Comment by ThunderAxe31** [comment]
> I'd have thought these would be on the profile, but that's probably a requirement for showing them on posts so w/e.
> 
> Having seen this overdone—one art community has **29 fields**—can I suggest limiting this to only platforms where TASVideos has a presence i.e. Discord, GitHub, and YouTube?

Makes sense to me. Don't forget about the TASVideos user page.

**Comment by adelikat** [comment]
The problem with this idea is that it doesn't age well.  The old forums had these, for things like icq.  These sites come and go. Even since the writing of this ticket, one of these has changed (twitter is now x). We do not want to have to keep updating the site code over time just to support this feature.

There is nothing stopping someone from linking these in their signature, so I don't see much value with built in support
