### ISSUE TITLE
Raise maximum avatar resolution

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/tasvideos#825]
In a forum post, the column that contains the avatar is wider now, so there is some blank space left unused, 70 pixels to be exact (35 for side). Since PC monitors and smartphone screens keep getting bigger, while the single pixels keep getting smaller, I think it would be a nice idea to raise the maximum avatar resolution. At very least raising the width to 170.

**Comment by Masterjun3** [comment]
The column width and the blank space depends on the size you're viewing at.

The minimum width of the desktop view is about 157px. But a resolution limit will most likely eventually be put into the html display itself, so that larger avatars will be scaled automatically, just like it currently does on the mobile view. The maximum avatar size will then be determined by the design itself. If we're not hosting avatars ourselves by that point, we should put a filesize limit and then we can let everyone choose their own resolution.

Side note: the physical pixels getting smaller has nothing to do with the pixels on websites. The important part here is the viewport. The viewport of my phone with 1080 physical pixels is 414px.

**Comment by ThunderAxe31** [comment]
> Side note: the physical pixels getting smaller has nothing to do with the pixels on websites.

It does. Having smaller pixels means that the same image appears smaller to the naked eye, and thus harder to look at. The solution is to use a bigger image, or to scale the same image to a bigger size than its original.

**Comment by Masterjun3** [comment]
No. It's the viewport, not the physical pixels.

**Comment by adelikat** [comment]
so the site doesn't actually enforce these requirements when you set your avatar, the rules are there so mods can handle it accordingly.  The text is a system page that can be changed by staff with appropriate permissions to edit system pages, so I do not consider that a development issue.  I recommend discussing a rule change on the forums, closing this ticket as no software change needs to be made.
