### ISSUE TITLE
Wiki renders [user:CoolUser] as a link even if CoolUser doesn't exist

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#828]
The old wiki only rendered [user:CoolUser] as a link if there was such a user and homepage. Thus, there are several places where this was used even if the users didn't have an account, in case they register it in the future.

The current wiki renders these as links even if the user doesn't exist, leading to a lot of broken links.

Example: Publication Text of https://tasvideos.org/4089M has several of these dead links.

**Comment by vadosnaprimer** [comment]
Yeah this module exists exactly so people with published movies could have their homepage automatically linked once they create one. Renaming wasn't considered tho. So maybe it should be approached differently? For now I agree that it shouldn't be a link until it's a working link (old site behavior).

**Comment by adelikat** [comment]
Who's going to type this, if they aren't a user though?  And note, the old site behavior was warranted because not all users had a homepage.  It now links to the profile page, which all users have.  The only time this issue could even apply reasonably, is name changes that were missed, that NEED TO BE FIXED.

The extra logic to check if the user exists is not warranted here imo

**Comment by Masterjun3** [comment]
Closing this because apparently the discussion continues at #1388 .
