### ISSUE TITLE
Organizing ROM info

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#855]
I think it should not be a per-publication or per-submission thing, but a per-game thing. So ideally it would have a dropdown when cataloging a submission and you'd just pick a ROM from the game DB. And if it's not there, you could use the current ROM UI to add to game DB. Only listing Good USA ROMs would be a good start.

But most importantly I wonder if it's possible to use some existing database to populate ROM info from it in one go. For example there should be hashes and ROM names used in Good sets, No-Intro, Redump, etc. It'd be a nightmare to enter everything by hand.

And yes for some games there are several files at once, like PSX, DOS, or Linux.

**Comment by adelikat** [comment]
Rom hashes are per game.  Once we build up a list, then new submissions for an existing game will have those to choose from.

But all submissions/publications do have to be associated with the specific rom that the submission uses (or that was sync was confirmed on).

If there is some kind of automated way to populate some of these, that's nice, but I worry about us having a lot of unused rom hashes cluttering up the database

**Comment by TiKevin83** [comment]
I wonder if there's a way to query the no-intro DB as an API to check ROM hashes instead of building our own database on the site

**Comment by meshuggahtas** [comment]
Can someone write down the steps of how it could be done now? Until then, here is my suggestion:
- **Getting source information**: Get goodset of platform X
- **Getting hashes**: Using Total Commander CTRL+A and Files > Create CRC Checksum file -> Create 1 file of hashes per platform X
This gets us lines like
```
864efb6b43e36bef50d01d381ca7bd83 *3D Asteroids (1987) (Atari) (Prototype).a78
e67a169b3a6432342ac9cbf9e6f95873 *3D Asteroids (1987) (Atari) (Prototype-NTSC).a78
46db223d11213986399ee9a83b6f2dfc *320btest by Schmutzpuppe (PD).a78
93ad29390482767123d73ae74663b90f *7800 Birthday by Mark Ball (V1.13).a78
```
- **Cleaning up**: Copy each line that has NTSC. This requires minimal development like reading each new line, checking for NTSC and/or other notions like [!] and dumping those lines.
- **Transforming and inputting hashes**: I guess the best solution would be somehow inserting it straight to the DB through a single SQL file/query
- Move on to next platform (X = next)

**Comment by vadosnaprimer** [comment]
We have game versions in our DB too, but I don't see region or version imported from the old site. Several movies had ROM region and version, which is currently only visible in submissions.

![изображение](https://user-images.githubusercontent.com/7092625/148638935-66a1fe7c-596a-4e5c-8841-47195893a091.png)

![изображение](https://user-images.githubusercontent.com/7092625/148638950-fca99dc7-3b61-4f57-8488-f0a858ef3b2c.png)

Not present at https://tasvideos.org/1746M and I can't find a way to view or edit, it just suggests me to add a new ROM entry.

What I'm getting at, is we can use information we already have to read only what we need from external ROM DBs, at least skipping games we don't have published.

**Comment by coolkirby2000** [comment]
> I wonder if there's a way to query the *no-intro* DB

> Get *goodset* of platform X

Should we be using No-Intro instead of GoodTools for ROM names? It's a more complete collection and the filenames are more descriptive; for example: "Pokemon - Blue Version (USA, Europe) (SGB Enhanced).gb" vs. "Pokemon - Blue Version (UE) [S][!].gb". They can also be more correct, like "Pocket Monsters - Ao" over GoodTools' "Pocket Monsters - Blue Version".

However, No-Intro names may be unfamiliar to newcomers choosing a ROM from the list (see [Pokémon Yellow's long names](https://tasvideos.org/446G)), may be missing some obscure pirate carts, and would require a minor site edit from "GoodTools name" to "No-Intro name" if we decide to change it.

I feel we should decide on this before we start filling the Rom tables for every game.

**Comment by vadosnaprimer** [comment]
Are hashsums the same for the same game for goodtools and no-intro? Am I confusing no-intro with headerless?

**Comment by meshuggahtas** [comment]
No, the hash is not the same. coolkirby2000 only suggests using a more descriptive names of No-Intro (ROMs that have been edited to remove intros) to be used. While general visitors might get better names, I'm unsure if this is required. The more descriptive names are the Display Name we use and they have been spent effort by editors to get the appropriate names AFAIK.

**Comment by vadosnaprimer** [comment]
Since (sane) emulators store hashes in movie files, sync is meant to be verified on the file that was used originally. And we don't dictate which set the roms should be from, so users can use one or another. Which means we will either have to put in hashes that don't match movies (bad) or we should have hashes from both DBs, at least have fields for both and it would be up to the cataloger which ones to fill in, depending on what was used in the movie (unpleasant but future-proof).

**Comment by coolkirby2000** [comment]
> Are hashsums the same for the same game for goodtools and no-intro?
From my testing with GB/C, yes. I checked hashes for Donkey Kong, Pokémon Silver, Pokémon Yellow, and SpongeBob LotLS, and they were the same between GoodGBx and No-Intro Game Boy/Color. From what I've read, it seems No-Intro has become a preservation project for clean ROMs on many systems, just like GoodTools. They even omit tags like [b] and [o], since they only retain good ROMs.

In the past few years, Google has shown more sites referring to the longer No-Intro names. The original [NKit-ISO converter] for GC/Wii (https://github.com/Nanook/NKit) also outputs the No-Intro names by default. However, historic publications on our site, like for Famtasia and FCEU, always used GoodTools' format as it was all that was available then, and some movies used the [b1] ROMs over [!].

14 submissions on our Workbench are in No-Intro format (having "USA" instead of "(U)[!]" for example) vs. 12 in the GoodTools format, which is about even. The remaining 10 are either a combination of the two formats or an unknown format (especially the Linux ones). Note that because the hashes match on the two sets, we [can't list both sets of names](https://github.com/TASVideos/tasvideos/issues/1030) due to that linked issue.

So we need standardized naming for the majority of platforms to help these users name their ROMs, as well as a custom user-provided field for DOS/Windows/Linux where the executable could have any name. If users will be seeing these names (I'm not sure if they can yet), should we have them vote on which names they prefer?

**Comment by adelikat** [comment]
With all the Game Version revamps, is there still a code change to make here? Or can this be closed?

**Comment by vadosnaprimer** [comment]
It was for initial brainstorming. For specific requests we can keep using specific issues.
