### ISSUE TITLE
Null System ID When Catelogging Movies For A Submission Makes Submission Page & Submission Table Throw An Exception

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASVideos/tasvideos#887]

**Comment by Masterjun3** [comment]
I can't fix this one because I'm not sure which side the error is on.
The code tells two conflicting ideas:

1. Explicit error if System is null:
https://github.com/TASVideos/tasvideos/blob/fb00367c4a6dc00297bccdbfeb993597bf080248/TASVideos.Data/Entity/Submission.cs#L112-L117

2. Explicitly saving a null System via https://github.com/TASVideos/tasvideos/commit/eafa5f7270a3be4698f5859bc5df0c74ded30329 `actually save if the user unselects a value`:
https://github.com/TASVideos/tasvideos/blob/fb00367c4a6dc00297bccdbfeb993597bf080248/TASVideos/Pages/Submissions/Catalog.cshtml.cs#L115-L118
