### ISSUE TITLE
Anyone with Cataloging Movies Permission Can Change Submission System ID and Framerate

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASVideos/tasvideos#888]
Keeping in mind **Editors** have this permission. Changing System ID on a submission on the old site was locked to Senior Staff, and changing framerate like this has dubious uses.

(This is also slightly mitigated by these changes don't take effect for the displayed System ID and time until an edit happens on the submission itself, although that still leaves Non-Senior Staff able to do this freely and Editors able to do this for their own movies).

**Comment by adelikat** [comment]
This is by design, if you don't trust someone with cataloging permissions, do not give it out to them.  Note that changing the system and framerate is trivial, which means changing it back is equally trivial.

It's by design that we need to have these fields editable on submissions since the parsers are not always 100% accurate.  And in the case of .gmv, we have no way information to parse to determine SegaCD or 32X.  We need to be able to tweak these values as needed
