### ISSUE TITLE
Allow tags at end of Youtube titles for alternative encodes (Such as Camhack)

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/tasvideos#912]
originally part of https://github.com/TASVideos/tasvideos/issues/811, I decided to split it into a separate issue so it can be seen.

There should be a way to enter a special tag that will be added into the title of the video, so for example if I put in a YT link for a camhack encode, I would type in a separate box "Camhack", then once it's added, the title gets that added at the end.

**Comment by vadosnaprimer** [comment]
For cases when movie name is too long, it may be better to add the tag after [TAS] and [Obsoleted] at the start instead.

**Comment by vadosnaprimer** [comment]
Not only is this relevant for youtube, but also for how video links are displayed on the site. Currently the site shows identical buttons and identical file links:

https://tasvideos.org/3570M

![изображение](https://user-images.githubusercontent.com/7092625/149567770-f77ec4d5-a5b0-4fac-af42-88d3abedb3a9.png)

![изображение](https://user-images.githubusercontent.com/7092625/149567801-dec47a86-43b0-43cd-a95c-dca6218033d0.png)

We put some notes into movie description about which file is which, but it always felt like a hacky approach, and it's better to tell which kind of link/button you're looking at.

Since we plan to support other kinds of extra encodes publishers may wish to create (Corey always wanted lossless), it makes sense to have a sensible system for those extra encodes.

For downloadable encodes we planned to add extra tokens to filenames, but for YT encodes that wouldn't work. So indeed it's better to add those tokens as strings to Mirror/Streaming fields. Yes that would imply having a new field in the db, but it has to exist in some form unless we ban all secondary encodes.

**Comment by adelikat** [comment]
Display name database column added, as well as fields on pub edit and submission publish page.  Just needs a movie module update to display the value

**Comment by adelikat** [comment]
Oh, and of course it still needs to be used in the youtube sync

**Comment by adelikat** [comment]
This work was done and deployed awhile ago
