### ISSUE TITLE
Add a button to jump to the bottom of the page

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#939]
When doing a lot of bookkeeping and reorganization, I have to constantly jump to the bottom of the page to access edit history, referrers, and sometimes other buttons only present there. Scrolling up is a very good function (even tho I'd prefer it to be an instant jump, because scrolling is distracting), but scrolling down is also needed very very often. For example when you only need to see the end of a thread.

**Comment by nattthebear** [comment]
![image](https://user-images.githubusercontent.com/1824709/149243779-3a744bd6-18e7-416a-bf61-6a3d07829582.png)

**Comment by ThunderAxe31** [comment]
Jump to top button already exists on the site: ![image](https://user-images.githubusercontent.com/36802254/149289139-4448e872-b122-45e6-b070-f4fceaf9e029.png) so it wouldn't too weird to add a jump to bottom button too.
However, I suggest to make any jumping button visible only for android devices, since PCs already have them on the keyboard.

**Comment by Masterjun3** [comment]
I wouldn't enjoy a button that's permanently on the screen which pressing accidentally would bring me all the way down.

**Comment by meshuggahtas** [comment]
Interesting scenario. 

1. Sites usually don't have scroll to bottom, because usually the design is "every edit link on top of the page" as well as "menubar on top of the page".

Wikipedia has this https://en.wikipedia.org/wiki/Portal:Biology

2. "For example when you only need to see the end of a thread."
I personally visited a lot of different discussion based websites in the past years and I personally would love to be able to flip the order of posts in threads (forum topics). The opening post rarely have the conclusion of a thread, so the newest information is the latest post.

I don't have suggestions, as both "feature request" introduces changes to everyone else, opt-in or not.

**Comment by adelikat** [comment]
A+ comments from natt, however, we have to consider mobile

**Comment by TiKevin83** [comment]
The jump to top button is already a bit of an anti-pattern because it requires a scroll listener and a fixed position button, I'm not sure I want to continue that trend

**Comment by nattthebear** [comment]
> A+ comments from natt, however, we have to consider mobile

I don't use that stuff, but isn't there some "drag two and three quarters fingers south by southeast across the screen while humming taps" gesture to scroll to bottom?

**Comment by meshuggahtas** [comment]
Personal opinions and suggestions as follows:

While the project doesn't have an official support matrix for the potential visitors' platform + browser combination, consider the following groups when giving complex fingering as a workaround:
- Watching from TV with a basic browser
- Mobile and tablet users
- Visitors with disabilities such as not enough limbs to perform such actions

This feature request while comes from an editor, might be a request for others as well. Requested feature requests should be considered as feature for everyone else for the sole reason to "If we are going to improve the quality of life of one user, we should improve all of them".

**Comment by nattthebear** [comment]
Oh I agree 100%, but I do wonder why the multi bazillion dollar companies don't have the same outlook when they make these devices on which it's difficult or impossible to perform basic functionality such as scroll to bottom.

**Comment by meshuggahtas** [comment]
Oh I can answer that too. If we are talking about for profit companies designing electronic devices that forgoes quality and functionality.

While there is no definitive platform+browser combination for this project, TASVideos community is powered by it's users. The site and it's members (and most importatnly our sturdy CEOs called (formerly Bisqwit and) adelikat and it's minions jokingly called back in the day, the various contributors and developers) have an actively listening and answering platform to share these problems and finding solutions for them.

The so called general consumption producer IT companies like Samsung, Huawei, Apple, you name it, are only interested in their profit (which is rarely based on giving quality service or service at all). They have money, they could have designed their products so we wouldn't have to deal with this. And they do completely the opposite of helping this issue.

Just a little side note about "scroll to top" and "scroll to bottom". Websites are usually designed as "navbar on top, main links on bottom", and the administrative buttons usually right next to the editable objects. Majority of these websites have vertically very long pages, and mobile users have a little resolution, making this issue an elephant instead of a simple bug.

Sorry for long text, I just wanted to share my viewpoints about this convenience issue

**Comment by meshuggahtas** [comment]
I've been looking for websites with both scroll to top and scroll to bottom but I only know and found scroll to top buttons for mobile viewing purposes.

I don't suggest the following, just surprised how convenient they did: GameFAQs has Table of content browsing for FAQs. You can jump to the right object you want. Now this comes with many extra development to do it and then again, will it be used by (mobile) visitors?

Can't figure out what is the ideal solution, because I can only think of:
- Only scroll to top button
- Scroll to top and scroll to bottom
- Next time someone wants to save current position to jump back
- Someone wants to save every page view position and cursor selection and automatically send a PDF report of their scrolling analytics

**Comment by TiKevin83** [comment]
IMO on the wiki a better solution would be to either duplicate or move the edit/history buttons to the top of the page if they're used so frequently, then we have no reason to have a "jump to bottom" button

**Comment by MemoryTAS** [comment]
> IMO on the wiki a better solution would be to either duplicate or move the edit/history buttons to the top of the page if they're used so frequently, then we have no reason to have a "jump to bottom" button

I would appreciate that immensely as somebody who is used to wikis with edit buttons on the top

**Comment by vadosnaprimer** [comment]
Yes!

**Comment by vadosnaprimer** [comment]
If the solution is moving the edit buttons, we need to move subpage display too.

**Comment by adelikat** [comment]
Some stuff was brought here that maybe could be other tickets but I'm labeling the original request as "won't fix" for reasons brought up
