### ISSUE TITLE
badly nested tags throw an exception

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#976]
Stumbled on this line in a post that crashes the forum parser:
[url=http://www.youtube.com/watch?v=1fwcjH2O_uU]Super Soccer TAS Germany vs. Belgium[url][/url]

Unforutnately, given the way the old forum did the helper buttons, this is likely very common.  if you click url, it only shows [url], and will autoclose it with [/url] when you submit.  An astute user might see the missing [/url] and add it them selves, which results in 2 of them.

The old parser managed to silently eat that extra one.  I'm not proposing we handle it the way the previous engine did, but we need it to not crash the whole page, given how common this could be.

**Comment by nattthebear** [comment]
Fixed with 65d1c2349745155b7b93bb1a25fa15b576ebfbcd.  The mismatch is sort of a red herring here; `[url][/url]` by itself is a simple repro.

As far as the mismatched tags go, after this fix it looks fine as the system renders something like this:

```html
<a href="http://www.youtube.com/watch?v=1fwcjH2O_uU">Super Soccer TAS Germany vs. Belgium</a><a href=""></a>
```

That's not really negotiable; the semantics for mismatched tags are actually used in a lot of places and a bunch of existing posts rely on them.
