### ISSUE TITLE
Let browsers use bfcache when logged in

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#979]
The so called "back/forward cache" is an optimization done automatically by browsers. It caches the whole page and related values to immediately restore them when going back or forward, thus the name.
There are certain conditions a page has to fulfill for browsers to enable this cache for the page. Our current pages are being blocked because their header sets "cache-control: no-store".

This feature would be useful because it makes browsing *much* faster. It also helps with textfields, which would be restored if someone accidentally clicks away. So implementing this would address #212 in most accidental cases where users browse away.

**Comment by Masterjun3** [comment]
Slight adjustment, we actually do have all conditions for bfcache, but only if not logged it. I changed the issue title to include this information.

**Comment by adelikat** [comment]
.net is overriding any attempt to do no-cache because there is an anti-forgery token.  Which is correct.  However, why does it think these pages need an anti-forgery token.  I don't understand

**Comment by meshuggahtas** [comment]
Is this issue related to this issue? https://github.com/TASVideos/tasvideos/issues/669
- 669: a situation where pressing back after submitting is not something we would like to support
- 669: it would make sense to give an explanation on why its not supported instead of generic browser message ERR_CACHE_MISS
- this 979: I guess it would make sense to have the same logic while logged in / not logged in on the Search scenario of staying/missing text

**Comment by Masterjun3** [comment]
Nah the easy part of this issue was just that the logout button on every page had an antiforgery token, which disables cache, fixed by #982.
